default_platform(:ios)

platform :ios do
  desc "Push a new release to App Store Connect"
  lane :release do
    deliver(
      submit_for_review: false,
      automatic_release: false,
      force: true, # Skips HTML report generation
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end
end
